import "./globals.css";

import type { Metadata } from "next";
import { CONST_HEADER_SLOTS } from "@/constants/navigation";

import Header from "./components/layout/header/header";

import {
  QueryClient,
  QueryClientProvider,
} from '@tanstack/react-query'

// ------------------------------------------------------------------

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// ------------------------------------------------------------------

const queryClient = new QueryClient()

// ------------------------------------------------------------------

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <QueryClientProvider client={queryClient}>
          <Header
            slots={CONST_HEADER_SLOTS}
          />
          {children}
        </QueryClientProvider>
      </body>
    </html>
  );
}
