import "./globals.css";

import React, { Suspense } from "react";
import type { Metadata } from "next";
import { CONST_HEADER_SLOTS } from "@/constants/navigation";

import Header from "../components/layout/header/header";
import NextQueryProvider from "../context/NextQueryProvider";

// ------------------------------------------------------------------

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// ------------------------------------------------------------------

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <NextQueryProvider>
          <Suspense fallback={<div aria-hidden="true" />}>
            <Header slots={CONST_HEADER_SLOTS} />
          </Suspense>
          {children}
        </NextQueryProvider>
      </body>
    </html>
  );
}
